#!/usr/bin/with-contenv bash

# make folders
[[ ! -e /config/config.js ]] && cp /defaults/config.js /config/config.js
[[ ! -L /usr/flood/config.js ]] && ln -s /config/config.js /usr/config.js && sed -i -e "s|<FLOOD_SECRET>|$FLOOD_SECRET|g" /config/flood/config.js && sed -i -e "s|<CONTEXT_PATH>|$CONTEXT_PATH|g" /config/config.js

#fix permissions
chown -R abc:abc /config
chmod 755 /usr/local/bin/curl

usermod -s /bin/bash abc