#!/usr/bin/with-contenv bash

# make folders
[[ ! -d /config/flood-db ]] && mkdir -p /config/flood-db
[[ ! -e /config/config.js ]] && cp /defaults/config.js /config/config.js
[[ ! -L /usr/flood/config.js ]] && ln -s /config/config.js /usr/flood/config.js && sed -i -e "s|<FLOOD_SECRET>|$FLOOD_SECRET|g" /config//config.js && sed -i -e "s|<CONTEXT_PATH>|$CONTEXT_PATH|g" /config/config.js

#fix permissions
chown -R abc:abc /config
chmod 755 /usr/local/bin/curl

usermod -s /bin/bash abc
